### ISSUE TITLE
Bug or not?

### ISSUE THREAD

**Issue by AndriyTonkikh** [coding-pythonx/supermarket-cashier#1]
i just copy/pasted ur code and see what isi happened:
C:\Users\KateFox777\PycharmProjects\pythonProject\venv\Scripts\python.exe C:/Users/KateFox777/PycharmProjects/pythonProject/main.py 
Press A to add product and Q to quit: A
Enter product: Egg
Enter quantity: 54
Press A to add product and Q to quit: A
Enter product: Biscuits
Enter quantity: 7
Press A to add product and Q to quit: Apple
Please select a correct option
Press A to add product and Q to quit: A
Enter product: Apple
Enter quantity: 45
Press A to add product and Q to quit: Q
Enter customer membership: Gold
Egg:$1x54=54
Traceback (most recent call last):
  File "C:\Users\KateFox777\PycharmProjects\pythonProject\main.py", line 63, in <module>
    makeBill(buyingData, membership)
  File "C:\Users\KateFox777\PycharmProjects\pythonProject\main.py", line 56, in makeBill
    billAmount += getPrice(key, value)
  File "C:\Users\KateFox777\PycharmProjects\pythonProject\main.py", line 28, in getPrice
    subtotal = priceData[product] * quantity
KeyError: 'Biscuits'

**Comment by stiperaketa** [comment]
im geting a simular error

**Comment by hydr0phobia** [comment]
Well i believe that you have to enter the product name exactly the way it is written in the dictionary, so, in this case it would be -"Biscuit" not "Biscuits".
However im getting a different type of confusion here, that is - why is the code saying -"The discounted amount is $",and the value it puts there is the total bill amount and not the dicount amount. How should i change the code to bring out the discount amount?
this is my code:

def enterProducts():
    buyingData = {}
    enterDetails = True
    while enterDetails:
        details = input("Press A to add products and Q to quit ")
        if details =="A":
            product = input("Enter Product: ")
            quantity = int(input("Enter quantity: "))
            buyingData.update({product:quantity})
        elif details == "Q":
            enterDetails = False
        else:
            print("Please  select a correct option!")
    return buyingData

def getPrice(product,quantity):
    priceData = {
        'Biscuit':3,
        'Chicken':5,
        'Egg':1,
        'Fish':3,
        'Coke':2,
        'Bread':2,
        'Apple':3,
        'Onion':3
    }
    subtotal = priceData[product]*quantity
    print(product+':$'+str(priceData[product])+'x'+str(quantity)+'='+str(subtotal))
    return subtotal
    
def getDiscount(billAmount, membership):	
    discount = 0	
    if billAmount >= 25:	
        if membership == 'Gold':	
            billAmount = billAmount * 0.80	
            discount = 20	
        elif membership == 'Silver':	
            billAmount = billAmount*0.90	
            discount = 10	
        elif membership == 'Bronze':	
            billAmount = billAmount*0.95	
            discount = 5	
        print(str(discount) + "% off for " + membership +	
              " " + "membership on  total amount: $" + str(billAmount))	
    else:	
        print("No discount on amount less than $25")	
    return billAmount

def makeBill(buyingData, membership):
    billAmount = 0
    for key, value in buyingData.items():
        billAmount += getPrice(key, value)
    billAmount = getDiscount(billAmount, membership)
    print("The discounted amount is $" + str(billAmount))


buyingData=enterProducts()
membership = input("Enter customer membership:")
makeBill(buyingData, membership)

**Comment by ReaZon17** [comment]
hydr0phobia I had the same issue ! 
The way I solved it was to first assign the variable "discount" a value, then print the message for each membership option, and then do the math for the discounted price.
That way it displays what I want ! 
I am a complete beginner, I don't know of better ways to do it, but I think this works pretty well.
So for the getDiscount function I did :

```
def getDiscount(billAmount, membership):
    discount = 0
    if billAmount >= 25:
        if membership == "Gold":
            discount = 20
            print(str(discount) + "% off for " + membership + " membership on total amount: " + str(billAmount) + "€")
            billAmount = billAmount * 0.80    
```        

        elif membership == "Silver":
            discount = 10
            print(str(discount) + "% off for " + membership + " membership on total amount: " + str(billAmount) + "€")
            billAmount = billAmount * 0.90

        elif membership == "Bronze":
            discount = 5
            print(str(discount) + "% off for " + membership + " membership on total amount: " + str(billAmount) + "€")
            billAmount = billAmount * 0.95    
   
    else:
        print("No discounts on amount less than 25€")
    return billAmount

And it displays :

20% off for Gold membership on total amount: 88€
The discounted amount is 70.4€

**Comment by sivasai7205** [comment]
The getDiscount function output is not giving us the total amount. That is giving us discounted amount only. As we are displaying the Total amount after we executing complete discount calculations and updating that with billAmount variable.

def getDiscount(billAmount, membership):
    discount = 0
    if billAmount >= 25:
        if membership == 'Gold':
            billAmount = billAmount * 0.80
            discount = 20
        elif membership == 'Silver':
            billAmount = billAmount*0.90
            discount = 10
        elif membership == 'Bronze':
            billAmount = billAmount*0.95
            discount = 5
        print(str(discount) + "% off for " + membership +
              " " + "membership on  total amount: $" + str(billAmount))
    else:
        print("No discount on amount less than $25")
    return billAmount

Thank you [ReaZon17](https://github.com/ReaZon17). 
Your suggestion helped me getting exact output.

**Comment by Rod-JS** [comment]
@hydr0phobia @ReaZon17 and @sivasai7205 I'VE FOUND IT!

Here's how I fixed the discount amount not being shown correctly:

```
def makeBill(buyingData, membership): #Function4 - calls Function3 to calculate discounted amount
    billAmount = 0
    for key, value in buyingData.items():
        billAmount += getPrice(key, value)
    **billAfterDiscount = getDiscount(billAmount, membership)**
    print('The discounted amount is $' + (str(billAmount - billAfterDiscount)))
```
I know it's three years later and now y'all are probably senior developers, but I had the same problem and it took me long time to solve it!

**Comment by ghost** [comment]
I refactored the code as a practice to learn OOP programming.

## Code

```python
from abc import ABC, abstractmethod
from typing import Dict, Optional

# Data layer (following DIP)
class ProductCatalog:
    def __init__(self):
        self._prices = {
            'Biscuit': 3, 'Chicken': 5, 'Egg': 1, 'Fish': 3,
            'Coke': 2, 'Bread': 2, 'Apple': 3, 'Onion': 3
        }
    
    def get_price(self, product: str) -> Optional[int]:
        return self._prices.get(product.title())
    
    def has_product(self, product: str) -> bool:
        return product.title() in self._prices

# Strategy pattern for discounts (following OCP)
class DiscountStrategy(ABC):
    @abstractmethod
    def calculate_discount(self, amount: float) -> tuple[float, int]:
        pass

class NoDiscount(DiscountStrategy):
    def calculate_discount(self, amount: float) -> tuple[float, int]:
        return amount, 0

class GoldDiscount(DiscountStrategy):
    def calculate_discount(self, amount: float) -> tuple[float, int]:
        return amount * 0.80, 20

class SilverDiscount(DiscountStrategy):
    def calculate_discount(self, amount: float) -> tuple[float, int]:
        return amount * 0.90, 10

class BronzeDiscount(DiscountStrategy):
    def calculate_discount(self, amount: float) -> tuple[float, int]:
        return amount * 0.95, 5

# Factory for discount strategies
class DiscountFactory:
    @staticmethod
    def get_discount_strategy(membership: str) -> DiscountStrategy:
        strategies = {
            'gold': GoldDiscount(),
            'silver': SilverDiscount(),
            'bronze': BronzeDiscount()
        }
        return strategies.get(membership.lower(), NoDiscount())

# Utility class for formatting (following DRY)
class BillFormatter:
    @staticmethod
    def format_currency(amount: float) -> str:
        return f"${amount:.2f}"
    
    @staticmethod
    def format_line_item(product: str, price: int, quantity: int, subtotal: float) -> str:
        return f"{product}: ${price} x {quantity} = ${subtotal:.2f}"
    
    @staticmethod
    def format_discount(discount_percent: int, membership: str, final_amount: float) -> str:
        if discount_percent > 0:
            return f"{discount_percent}% off for {membership.title()} membership. Final amount: ${final_amount:.2f}"
        return "No discount applied"

# Input handler (following SRP)
class InputHandler:
    @staticmethod
    def get_products() -> Dict[str, int]:
        buying_data = {}
        while True:
            choice = input("Press A to add product and Q to quit: ").upper()
            if choice == "A":
                product = input("Enter product: ").strip()
                try:
                    quantity = int(input("Enter quantity: "))
                    if quantity > 0:
                        buying_data[product] = buying_data.get(product, 0) + quantity
                    else:
                        print("Quantity must be positive.")
                except ValueError:
                    print("Please enter a valid number for quantity.")
            elif choice == "Q":
                break
            else:
                print("Please select a correct option")
        return buying_data
    
    @staticmethod
    def get_membership() -> str:
        return input("Enter customer membership: ").strip()

# Main business logic (following SRP)
class PriceCalculator:
    def __init__(self, catalog: ProductCatalog):
        self.catalog = catalog
    
    def calculate_item_price(self, product: str, quantity: int) -> tuple[float, bool]:
        price = self.catalog.get_price(product)
        if price is None:
            return 0.0, False
        return float(price * quantity), True

class BillingService:
    def __init__(self, catalog: ProductCatalog, calculator: PriceCalculator):
        self.catalog = catalog
        self.calculator = calculator
    
    def generate_bill(self, products: Dict[str, int], membership: str) -> None:
        total_amount = 0.0
        
        print("\n--- BILL ---")
        # Calculate line items
        for product, quantity in products.items():
            subtotal, success = self.calculator.calculate_item_price(product, quantity)
            if success:
                price = self.catalog.get_price(product)
                print(BillFormatter.format_line_item(product.title(), price, quantity, subtotal))
                total_amount += subtotal
            else:
                print(f"Warning: {product} not found in catalog")
        
        print(f"\nSubtotal: {BillFormatter.format_currency(total_amount)}")
        
        # Apply discount if applicable
        if total_amount >= 25:
            discount_strategy = DiscountFactory.get_discount_strategy(membership)
            final_amount, discount_percent = discount_strategy.calculate_discount(total_amount)
            print(BillFormatter.format_discount(discount_percent, membership, final_amount))
        else:
            print("No discount on amounts less than $25")
            final_amount = total_amount
        
        print(f"Final Amount: {BillFormatter.format_currency(final_amount)}")

# Main execution
def main():
    # Dependency injection
    catalog = ProductCatalog()
    calculator = PriceCalculator(catalog)
    billing_service = BillingService(catalog, calculator)
    
    # Get user input
    products = InputHandler.get_products()
    membership = InputHandler.get_membership()
    
    # Generate bill
    billing_service.generate_bill(products, membership)

if __name__ == "__main__":
    main()
